### ISSUE TITLE
Canvas is missing fonts

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/setup-cml#23]
This is something reproducible in the container at least.

![image](https://user-images.githubusercontent.com/414967/109966922-166ae980-7cf1-11eb-9ef8-3a483dad09aa.png)

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, I have been unable to reproduce it with [iterative/cml_base_case](https://github.com/iterative/cml_base_case) and `docker://dvcorg/cml-py3` but the plot in the latest example is not the same as the one in your screenshot. Can you please provide some additional directions to reproduce this issue?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 this issue can be seen here in the comments. The matrix with ubuntu container is having that issue.
