### ISSUE TITLE
Build mechanism

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/setup-cml#24]
Github actions needs by convention to override the mayor version doing a forced push. 
Now it's done manually  and should be done in the CI when merging into master.

**Comment by 0x2b3bfa0** [comment]
### Quote from @casperdcl https://github.com/iterative/setup-cml/pull/42#discussion_r711077808

> The [tagging approach for actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) is very different from tags on normal repos.
> 
> - https://github.com/Actions-R-Us/actions-tagger is rubbish
> - `git push origin :refs/tags/{tag} && git tag --force {tag} && git push origin {main} --tags` is also rubbish
> 
> You need `git tag v1.x.x && git tag -f v1 && git push --tags -f`
> 
> I would suggest:
> 
> - closing this PR unmerged
> - rename `master` to `v1` and use a hybrid of
>   + [branch approach for actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-branches-for-release-management) for major (i.e. `@v1`, `@v2`) pointers
>   + tags for semver (i.e. `@v1.x.x`) pointers
>     * ideally start writing release notes for these but accept that no `workflow.yml` file can enforce this

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, does anybody dislike this approach? In the meanwhile, I'm going to request again ⚡ permissions on the almighty `#infrastrutcure` channel.
