### ISSUE TITLE
Installing unpinned vega-lite package breaks Node 12 support

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/setup-cml#40]
We're installing all the `vega` packages without any version pinning, and with methods other than `package-lock.json` 🙀 

https://github.com/iterative/setup-cml/blob/fbe960885f26b2965cd88995323ad83da1e662c8/src/utils.js#L35-L37

Tests were failing for https://github.com/iterative/setup-cml/pull/38* because we depend on [vega-lite](https://www.npmjs.com/package/vega-lite) and it's trying to use a nullish coalescing operator `??` on Node JS 12, but [wasn't supported](https://node.green/#ES2020-features--nullish-coalescing-operator-----) until 14.

See also [vega/vega-lite#v5.0.0](https://github.com/vega/vega-lite/releases/tag/v5.0.0) release notes: _no more ES5 builds._

***

\* Tests were failing [also for the `master` branch](https://github.com/iterative/setup-cml/runs/3528795329?check_suite_focus=true#step:13:13); we know it thanks to the scheduled tests introduced with #37.

**Comment by 0x2b3bfa0** [comment]
### Pinning behavior of [actions/setup-node](https://github.com/actions/setup-node#usage)

> _The node-version input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one._
> 
> _For information regarding locally cached versions of Node.js on GitHub hosted runners, check out GitHub Actions Virtual Environments._

**Comment by 0x2b3bfa0** [comment]
### Default Node JS version on GitHub Actions

GitHub Actions Virtual Environments are in Node **14** since 2020-11-02, as per https://github.com/actions/virtual-environments/issues/1953#issue-734293245, so supporting 12 is not neccessary anymore, but we're going to keep it around for compatibility.

**Comment by 0x2b3bfa0** [comment]
### Should we install `vega` and related packages?

* It looks like it might not be the case. See https://github.com/iterative/setup-cml/pull/8 for more information.

**Comment by DavidGOrtega** [comment]
We decided to include vega as far as I remember, it was removed for a while a then we came back
