### ISSUE TITLE
Require users to be responsible for Vega and other dependencies

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/setup-cml#47]
### Context

* #8
* #40

### Code

https://github.com/iterative/setup-cml/blob/a7b00a80a68861804bbdd73396f56b81d5ce999f/src/utils.js#L37

### Proposals

@DavidGOrtega suggested in #8 that “Vega should be installed as a separate action”

**Comment by DavidGOrtega** [comment]
No, we finally decided to not do that since many workflows were broken.

**Comment by 0x2b3bfa0** [comment]
Alright, then should we keep them here or add them as optional dependencies on CML's `package.json` and install them only on GitHub Actions?

**Comment by casperdcl** [comment]
:+1: optional deps + Docker using said optional deps directly (rather than hardcoding into the `Dockerfile`).

**Comment by 0x2b3bfa0** [comment]
Given that [the official Vega-Lite documentation recommends using `npx` directly](https://vega.github.io/vega-lite/usage/compile.html#cli),[^1] managing the installation of dependencies behind the back of users is a bit of a footcannon.



> _Explicit is better than implicit_ — [PEP 20](https://peps.python.org/pep-0020)

[^1]: A bit fallacious; standalone usage would be rather lengthy: `npx --yes --package canvas --package vega-lite {command}` where `{command}` is `vl2png` or similar.

**Comment by dacbd** [comment]
if we want to ditch this from the action I'd say...

Step 0:
- create a public timeline for following

Step 1:
- create a flag to additionally install vega-cli tools, default true
- use action's mechanism to warn users

Step 2:
- change the default for the flag to false

Optional step 3:
- remove from the codebase and create simpler bash/composite action to npx or npm -g install vega cli tools

**Comment by dacbd** [comment]
setup-cml@v2 implements step-1 of the above, going to close this issue and force step-2 if the npm install starts to fail for users.
