### ISSUE TITLE
composite action

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#54]
Using a [composite](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) rather than NodeJS action would potentially solve #53 (and https://github.com/iterative/cml/issues/825) as well as make things faster, smaller, and more secure (no need to review/keep in sync/maintain separate `src/` & `dist/`)

**Comment by dacbd** [comment]
by composite action, you mean having a step for `setup-node` then the existing NodeJS action `setup-cml`

**Comment by casperdcl** [comment]
No I mean deleting `**.js` and simply using a few lines of `bash` directly in `action.yml`. See e.g. https://github.com/casperdcl/deploy-pypi/blob/v2/action.yml

**Comment by dacbd** [comment]
hmm, is windows a common CI env people use? Does actions use git bash on windows or something (rhetorical, I can google), I have made/used a few composite actions as well but never had to worry windows use. https://github.com/iterative/setup-cml/blob/d20d4aafa96eaffcae0117576b03079b70b163c9/.github/workflows/check.yml#L13-L16

**Comment by dacbd** [comment]
sounds like a good v3 branch/tag

**Comment by dacbd** [comment]
Perhaps some other these can best be handled or expanded on via: https://github.com/iterative/setup-tools.

Feel free to reopen if you disagree.

**Comment by dacbd** [comment]
with setup-cml@v2 being a bit of a toolchain rewrite I'm going to close. We can readdress the mechanisms defined in the `action.yml` size/speed/reliable/security concerns pop up again.
