### ISSUE TITLE
windows tests failing

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#56]

**Comment by 0x2b3bfa0** [comment]
Context on iterative/cml#865

**Comment by 0x2b3bfa0** [comment]
Not anymore; #60.[^1]

[^1]: Borderline [malicious compliance](https://en.wikipedia.org/wiki/Malicious_compliance); maybe what failed previously is still failing, but we aren't testing it anymore and it's definitely not a priority.

**Comment by 0x2b3bfa0** [comment]
🔔 @iterative/cml for deontological considerations
