### ISSUE TITLE
binary install

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#57]
Due to https://github.com/iterative/cml/pull/842 and following https://github.com/iterative/setup-dvc/blob/v1/src/utils.js, we could use [release binary assets](https://github.com/iterative/cml/releases) directly to remove any dependency on a particular version of `nodejs`/`npm` being installed.

See [logic for obtaining latest asset URL](https://github.com/iterative/dvc.org/blob/master/.github/workflows/update.yaml)

**Comment by 0x2b3bfa0** [comment]
[Relevant comment on Discord](https://discord.com/channels/485586884165107732/728693131557732403/946364212563824690)

**Comment by dacbd** [comment]
setup-cml@v2 now uses cml binaries from the cml release assets
