### ISSUE TITLE
Add more logging to increase visibility of `cml` setup.

### ISSUE THREAD

**Issue by dacbd** [iterative/setup-cml#70]
print the `version` of cml, what is the version of "latest"?
 See #51 for some "old" context

**Comment by nibilin33** [comment]
when --version command failed, i use npm-api to query the latest version and print it , is it ok?

**Comment by dacbd** [comment]
@nibilin33 not entirely sure what you mean by `npm-api` I'm guessing that should be fine, you are welcome to open any PRs as a draft and ask questions on that as well.
