### ISSUE TITLE
speedup with caches

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#83]
CI jobs taking a few seconds to setup is painful. By comparison, https://github.com/actions/setup-python & https://github.com/actions/setup-node support caching.

See https://github.com/mvshmakov/test-dvclive-studio/blob/e406619be56905bb5650aaff3d41d2c6123dcdce/.github/actions/setup_environment/action.yaml#L29-L57 for using caches to speedup CML setup. /CC @mvshmakov

Related: #54

**Comment by dacbd** [comment]
setup-cml@v2 now uses the GitHub actions tool cache.
